version: "3.9"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: unless-stopped
volumes:
  pgdata:
